### ISSUE TITLE
Bug - After installing this Intellibot plugin, no lookups are working.

### ISSUE THREAD

**Issue by Flukester69** [lte2000/intellibot#10]
In fact it appears worse than before, minus the error in Pycharm. Now everything has underlines.

Running Pycharm 2020.1
Running Python 3.7

Actions performed:
Removed old Intellibot
Installed new Intellbot, the jar from github via Install from disk

**Comment by owlette** [comment]
I get "fail to load plugin desscriptor" error when trying to install the .jar locally. Some issue in the file definition?

**Comment by mecanda12** [comment]
I install the new version 0.10.143.390 , there is no issue.

**Comment by lte2000** [comment]
no problem here for long time. please check your env and try latest version of this plugin.
