### ISSUE TITLE
Variables are not recognized inside FOR syntax

### ISSUE THREAD

**Issue by zastress** [lte2000/intellibot#13]
I have a code with a simple FOR syntax, like the one below:

`FOR    ${INDEX}    IN RANGE    1   4

       Create User With Name            ${USER-PREFIX}28-user${INDEX}

END`

The `${INDEX}` variable on the second line is underlined as not recognized inside Pycharm.

**Comment by mecanda12** [comment]
I guess that was Pycharm issue. Now is resolved in new Pycharm version 2020.2. Please see below screen-short. 
![image](https://user-images.githubusercontent.com/32083604/88843790-aec74b80-d1af-11ea-93ec-0f819c424c8e.png)

**Comment by lte2000** [comment]
I'm using Pycharm 2019.1.3, it is OK. Please see below screen-shot.
<img width="304" alt="${INDEX}" src="https://user-images.githubusercontent.com/35422407/96917810-ebb78b80-14db-11eb-9a2c-343cd09a3fc4.png">

**Comment by zastress** [comment]
Works for me now too. Thanks.
For info, I have praised your work in my YouTube tutorials ( https://youtu.be/VYlpCrxLsEA ) and I also shared the repository with the Robot Framework community on slack. You have a lot of our attention :). Please continue to contribute!

**Comment by lte2000** [comment]
Your video is so cool. It comprehensively describes the main problems encountered before and their current solutions. Thank you!

**Comment by zastress** [comment]
Tou're welcome. You earned the credit ;)

**Comment by zastress** [comment]
Fixed

**Comment by lte2000** [comment]
@zastress Thanks for you video, I have linked your YouTube tutorials ( https://youtu.be/VYlpCrxLsEA ) in the plugin (name: intellibot #patched) overview page in marketplace https://plugins.jetbrains.com/plugin/17424-intellibot-patched
If any concern, please let me know.

**Comment by zastress** [comment]
That's great, man! Thanks a lot for the feedback and for linking the video.
Glad you uploaded it to marketplace.
