### ISSUE TITLE
Just say thank you

### ISSUE THREAD

**Issue by thyarles** [lte2000/intellibot#16]
Hi, @lte2000,

Just to say thank you for your amazing work keeping this plugin updated. If you have an way to donation, please, let me know.

**Comment by lte2000** [comment]
You're welcome.

**Comment by tminakov** [comment]
I'd like to join in saying Thank You for what you did and continue to develop. 
PyCharm is my favorite IDE, Robot Framework is my go-to choice for 5 years now, and the lack of stable plugins for it was troubling all along. 
Not any more, and it's all thanks to you; it was a relief to see the various existing bugs of the original plugin fixed, and the support of new syntax - and mostly, the new libraries' structure! - a big productivity boost. 

I support OP in that you should add a way to donate as a way to express the users gratitude/say thank you.
