### ISSUE TITLE
Support for the new IF in Robot Framework 4.x

### ISSUE THREAD

**Issue by sd-yazzoom** [lte2000/intellibot#20]
I'm currently using the 4.0b1 of robot framework and the good news is that intellibot is working quite nicely with the newer robot framework version, so not much will need to be changed to make it compatible I think.

One thing that needs changing however is support for the new IF (ELSE ELSEIF).

As a workaround I'm currently defining the new syntax as keywords (in a common resource file I use for all my tests):

```
# Preliminary support RF 4.x

IF
    No Operation

ELSE
    No Operation

ELSE IF
    No Operation

```

The framework is smart enough to ignore it, and the plugin is smart enough to no longer see IF, ELSE and ELSE IF as missing keywords! (END was already covered by the new FOR loop)

This is very "hacky" though, and I would love to see a more robust fix when the new RF version will be launched.

**Comment by lte2000** [comment]
code in dev_0.10.143.392.
Please download and install the intellibot.jar from https://github.com/lte2000/intellibot

**Comment by sd-yazzoom** [comment]
thanks @lte2000 ! Installed it and will give some feedback/close the ticket after playing around with it for a while. First impression... awesome! :-)

**Comment by sd-yazzoom** [comment]
Been using it for a few days now, works like a (Py)charm, thanks again @lte2000 !
