### ISSUE TITLE
Error during installation process in PyCharm

### ISSUE THREAD

**Issue by achmielarski** [lte2000/intellibot#21]
Hi,
when I tried to install the plugin from a disk I have received a message
"Fail to load plugin descriptor from file intellibot.jar".

![error_pycharm](https://user-images.githubusercontent.com/8530702/108411044-7315d100-7228-11eb-903a-3da20313badc.png)

PyCharm - Community version 2020.3.3.

Regards,
Andrew

**Comment by lte2000** [comment]
Not reproduced.
Could you check whether the file is downloaded correctly?
The md5sum of the latest version (0.10.143.392) is:
$ md5sum intellibot.jar
1fdf45c9f6a0fa6bab8971e450719ac2 *intellibot.jar

**Comment by achmielarski** [comment]
Hi,
thanks for your help.

New downloading has resolved the issue.
