### ISSUE TITLE
builtin keywords of resource files are not recognized

### ISSUE THREAD

**Issue by zrqsar** [lte2000/intellibot#27]
Error : 
No keyword with name 'Make Connection' found.

Make Connection is a keyword in DBLibrary2.py with below implementation : 

		def make_connection(hostname, port, sid, username, password):
			global connection
			global cursor
			my_dsn = cx_Oracle.makedsn(hostname,port,sid)
			connection = cx_Oracle.connect(username, password, dsn=my_dsn)
			cursor = connection.cursor()
			
DBLibrary2 is imported in .robot file as "Library    DBLibrary2" under *** Settings ***

code : Run keyword if    '${system}' == 'Windows'    Run keyword    Make Connection

pycharm version : 2020.3

**Comment by lte2000** [comment]
@zrqsar I can't reproduce the issue you decribed.

I just create DBLibrary2.py with the function make_connection:
![image](https://user-images.githubusercontent.com/35422407/125916395-cf25cfde-76da-4eca-8ac0-dc9d484cf60c.png)

and create robot file to use that keyword,  it can resolve that keyword, and can jump to that function with ctrl+click:
![image](https://user-images.githubusercontent.com/35422407/125916538-b547605f-d538-4333-9635-c1b1c91d3075.png)
