### ISSUE TITLE
Variable ${EXECDIR} is not recognized

### ISSUE THREAD

**Issue by diegoquirino** [lte2000/intellibot#28]
**Given** that I use robotframework "environmental variable" ${EXECDIR} into the values for _Variable_ and _Resource_ into Settings session

**When** I reference files that exists

**Then** referenced variables or keywords found (PyCharm IDE no "red" marks)

**BUG** "red" marks into PyCharm IDE as the variables or keywords _were not found_ but they are there - in referenced variable and resource files (see attached image)

![error_robot_plugin](https://user-images.githubusercontent.com/1110313/126190448-e5baeba1-83e2-4d81-a083-06cf8577cd59.png)

**Comment by lte2000** [comment]
First of all,  ${EXECDIR} is the absolute path to the directory where test execution was started from It is not the directory where the test data located. The plugin can't know where the test execution will be started from.

But now, you can provide the value for any variable yourself in Robot Option.
For example, input:
${EXECDIR}=/path/to/execution
${ANYVAR}=/path/to/VAR
Then
Library    ${EXECDIR}/aa/bb/${ANYVAR}/lib.py
will be
Library    /path/to/execution/aa/bb/path/to/VAR/lib.py

Note: it just do simple string replacement, no any other function.

Please try dev_0.10.143.397 from https://github.com/lte2000/intellibot

**Comment by diegoquirino** [comment]
Thank you @Ite2000
**The instructions solucioned my problem.**
