### ISSUE TITLE
On Macbook: keyword cannot jump when it has return variable 

### ISSUE THREAD

**Issue by kritsadakorn1** [lte2000/intellibot#29]
```
*** Test Cases ***
TC01
    ${messgae}  Test On MacBook     intellibot
    Test On MacBook     intellibot

*** Keywords ***
Test On MacBook
    [Arguments]   ${name}
    ${message}      set variable    hello ${name}
    [Return]    ${message}

```
Note:
On Macbook, this keyword **cannot** jump to keywords section
 ${messgae}  Test On MacBook     intellibot
![image](https://user-images.githubusercontent.com/86505666/128349795-ce6fedba-abe6-430e-a243-9a7adce4576d.png)

On Macbook, this keyword can jump to keywords section
Test On MacBook     intellibot
![image](https://user-images.githubusercontent.com/86505666/128350002-4a9557d7-9dba-4e1b-a733-11479c2ac01b.png)

It works fine on Windows.

**Comment by kritsadakorn1** [comment]
for this issue, "quick definition" does not work too.

**Comment by kritsadakorn1** [comment]
it not a defect, issue may be plugin conflict.
uninstall plugin, robot framework support, install only plugin intellibot. it works fine.

**Comment by lte2000** [comment]
solved by issue author.
