### ISSUE TITLE
[IntelliBot Robot Framework ALM Converter] Search keywords with "-", "?" prefixes

### ISSUE THREAD

**Issue by betapl3b** [lte2000/intellibot#37]
Hello @lte2000 !
I like your version of plugin and want to use it with Robotframework ALM converter. The thing is: this converter requires some tricky syntax, so all of keywords start with "-" or "?" symbol.
So instead of
`Open main page`
`Check page title`
it will look like 
`- Open main page`
`? Check page title`
I believe it's enough to find "Search for reference" code and add some conditions to ignore this prefix or to add this symbols to 'Gherkin-like' prefixes list.
I tried to fork and build your plugin by myself but faced an issue with com.jetbrains.python.psi lib for some reason.
I wanted to ask your help with that issue or just build that fix for me in separate branch (or send jar via email) if you know how to implement it quikly.
Waiting for your reply!

**Comment by lte2000** [comment]
Do you mean in you Test Cases, it like:
```
*** Test Cases ***
Test
    - Open main page
    ? Check page title
```
While your keyword definition is like:
```
*** Keywords ***
Open main page
    Log    a

Check page title
    Log    b
```

And you want resolve "- Open main page" in your Test Cases to "Open main page"?

**Comment by betapl3b** [comment]
Exactly! And most of my keywords are from custom python library if it matters.

**Comment by lte2000** [comment]
Please try the attached intellibot. "[intellibot.zip](https://github.com/lte2000/intellibot/files/7248981/intellibot.zip)"

**Comment by betapl3b** [comment]
@lte2000 it's perfect, appreciate it!

**Comment by robco** [comment]
@betapl3b , any plans to include this to the main branch?

**Comment by betapl3b** [comment]
@robco I am not owner of the repo.
Actually this feature is quite specific (only for ALM convertor users) and I think there is no need to merge it.
For someone who needs it, I think, this .zip build is enough

**Comment by robco** [comment]
@betapl3b, this is not about "ALM Convertor". Robot Framework supports custom prefixes which can be utilized by various "conventions approaches". For example Gherkin, etc. 
Having this available as custom build is fine as long as new Intellibot version will be/was released. Newer versions of Intellibot will make this custom build outdated and probably incompatible in case PyCharm will change something in the middle..
