### ISSUE TITLE
Add support for "Task" execution type

### ISSUE THREAD

**Issue by zastress** [lte2000/intellibot#4]
New in RF 3.1: https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#terminology-configuration-to-support-robotic-process-automation-rpa

Already solved here: https://github.com/jamofer/intellibot/commit/962c5704e519c9de09645f11c229653084a43b1f

**Comment by lte2000** [comment]
We in QA has no opportunity to use "Tasks" yet. And supplement tools only read "Test Cases" contents in the results. And mixture of "Test Cases" and "Tasks" (even in different files) will cause RobotFramework error.

So it is a good choice to let it still show "Tasks" as syntax error, like a sign of "this table is not supported yet". Maybe in the future, we have a chance to use it.

**Comment by lte2000** [comment]
@zastress  please try https://github.com/lte2000/intellibot/raw/c697374f8b00a0f1fd0d25f70c7bb36c9fa78661/intellibot.jar

**Comment by lte2000** [comment]
fixed in [v0.10.143.398](https://plugins.jetbrains.com/plugin/17424-intellibot-patched/versions/stable/134225)
