### ISSUE TITLE
It can not find "FOR" KEYWORD

### ISSUE THREAD

**Issue by EVAN409812904** [lte2000/intellibot#40]
can not find "FOR" KEYWORD 
![image](https://user-images.githubusercontent.com/93566031/140058644-8712f747-4dc8-4e48-b570-99dca6510c46.png)
![image](https://user-images.githubusercontent.com/93566031/140059147-cbce09fa-eaa1-4214-acbe-ec56ec409837.png)

and can not find DateTime
![image](https://user-images.githubusercontent.com/93566031/140058976-d6af4ea2-ae52-4e95-84f1-aa13a23155ad.png)

**Comment by lte2000** [comment]
FOR is not a keyword.

DateTime is robotframework BUILT-IN library, it works well. Could you check your python and pycharm project settings?

![image](https://user-images.githubusercontent.com/35422407/140239120-92aaa731-6314-4550-a8d0-ba970b9e3010.png)

**Comment by EVAN409812904** [comment]
> FOR is not a keyword.
> 
> DateTime is robotframework BUILT-IN library, it works well. Could you check your python and pycharm project settings?
> 
> ![image](https://user-images.githubusercontent.com/35422407/140239120-92aaa731-6314-4550-a8d0-ba970b9e3010.png)

emm...  i find another DateTime.py in wxPython, so i remove it then work well, is it a bug?
by the way, can't this plugin prompt the "FOR" like RIDE.    e.g END，IN

**Comment by lte2000** [comment]
For the DateTime.py, please check and adjust python module search order in your project.

For auto-completion of FOR, END, IN, will be implemented in future. But I think this is not urgently needed, because, after all, only 2~3 characters need to be input, while with auto-completion it also need 2~3 key press.

**Comment by lte2000** [comment]
Auto-completion of FOR, END, IN is implemented Version 0.12.191.8026
