### ISSUE TITLE
Keywords with embedded arguments don't work

### ISSUE THREAD

**Issue by stavstrom** [lte2000/intellibot#43]
Why have embedded arguments stopped working? It worked in dev_0.10.143.395, but has stopped working after that. 

Simple example:

![image](https://user-images.githubusercontent.com/46621938/145821664-b8bf739e-9381-482a-8d77-a95fbe501246.png)

Embedded arguments are working for keywords that are defined in python libraries, but not for keywords that are defined in test suites or in resources.

**Comment by lte2000** [comment]
@stavstrom , please try attached patch v0.11.191.8026.1
[intellibot.zip](https://github.com/lte2000/intellibot/files/7709663/intellibot.zip)

There is other potential issue for keywords defined in python libraries, but since it still works well now, I didn't touch that part.

**Comment by stavstrom** [comment]
@lte2000 the patch works, thank you for your quick support :-)

**Comment by lte2000** [comment]
fixed in Version 0.12.191.8026
