### ISSUE TITLE
Resolving reference taking forever for some keywords

### ISSUE THREAD

**Issue by YevgenyFarber** [lte2000/intellibot#45]
Resolving reference hangs for some keywords, can you please tell me where to look for fixing this?

**Comment by snackwell** [comment]
Exactly，Here meet the same problem, Resolving reference hangs also.

**Comment by lte2000** [comment]
Hello, can you provide an example to reproduce?

**Comment by YevgenyFarber** [comment]
For me it was import issue, once I have removed some import it's working like charm,
@snackwell check your imports some of them causing this behavior
