### ISSUE TITLE
Support Robot Framework 5.0

### ISSUE THREAD

**Issue by YevgenyFarber** [lte2000/intellibot#48]
Hi, 

Is Support Robot Framework 5.0 planned?

**Comment by lte2000** [comment]
Hello,
I'm still busy writing scripts with old version of robot framework, no chance to use the v5.0.
Can you provide a list of items need to do to support Robot Framework 5.0 (or what issue you met when use this plugin with Robot Framework 5.0)?
Thanks!

**Comment by YevgenyFarber** [comment]
Hi,

Below keywords are not supported:

[TRY/EXCEPT](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#try-except)
[WHILE](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#while)
[Inline IF](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#inline-if)
[BREAK and CONTINUE](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#break-and-continue)
[RETURN](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#return)

**Comment by lte2000** [comment]
> Hi,
> 
> Below keywords are not supported:
> 
> [TRY/EXCEPT](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#try-except) [WHILE](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#while) [Inline IF](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#inline-if) [BREAK and CONTINUE](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#break-and-continue) [RETURN](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#return)

Hello @YevgenyFarber ,
Please try the attached patch to support rf-50.
[intellibot.zip](https://github.com/lte2000/intellibot/files/8832219/intellibot.zip)

**Comment by YevgenyFarber** [comment]
Incredible, Thanks, working!!!
