### ISSUE TITLE
intellibot does not resolve environmental variables like %{ROBOT_ROOT}

### ISSUE THREAD

**Issue by MichalChapko** [lte2000/intellibot#49]
when using environmental variables in robot scripts intellibot fail to resolve them.

%{ROBOT_ROOT} is being highlighted as not resolved

As a result the imported keywords are not available if used in Library  %{ROBOT_ROOT}/some.py

This cause big inconvenience in writing the code using a plugin.

Why not to add a library dir to source roots -> I tried that. Then Classes and keywords are resolved in IntelliJ, but does not work for some reasons during tests execution.

**Comment by lte2000** [comment]
It will not resolve variables to its value, including environment var and global var.
But if the environment var is in the libarary/resource path, you can replace the environment var with string defined in the options, For example:
%{ROBOT_ROOT}=/home/robot

![image](https://raw.githubusercontent.com/lte2000/intellibot/master/wiki/robot_options/new_options.png)

**Comment by MichalChapko** [comment]
Thanks for the explanation.
I understand the behavior of plugin will not be extended to support.
With given explanation I'm closing the ticket .
