### ISSUE TITLE
Keywords in SeleniumLibrary are not jumped to via Ctrl-Click

### ISSUE THREAD

**Issue by darrylwhiting** [lte2000/intellibot#5]
Using the zip file from: [Issue #255 Link](https://github.com/millennialmedia/intellibot/issues/225#issuecomment-557388320)

- Search Keywords in Sub-packages is Enabled in Plugin Settings, Max Transitive set to "99"

- My system path begins with: PATH=C:\Python37-32\Scripts\;C:\Python37-32\;

- Other keywords are jumped to, for example keywords from BuiltIn.py

This is just one example of an unrecognized keyword (pipes added for readability):
```
${element}= | get WebElement | css:span#blah | 
```
However, "get_webelement" is in the file
C:\Python37-32\Lib\site-packages\SeleniumLibrary\keywords\element.py 

```
class ElementKeywords(LibraryComponent):

    @keyword(name='Get WebElement')
    def get_webelement(self, locator):
        """Returns the first WebElement matching the given ``locator``.

        See the `Locating elements` section for details about the locator
        syntax.
        """
        return self.find_element(locator)
```

**Comment by lte2000** [comment]
solved in dev_0.10.143.387.
Please download and install the intellibot.jar from https://github.com/lte2000/intellibot

**Comment by darrylwhiting** [comment]
Thank you for the quick turnaround. I will download soon and report back.

**Comment by darrylwhiting** [comment]
I was able to to get this installed today, closing the issue since the new build fixed it.
