### ISSUE TITLE
very high CPU usage ~ 55-70%

### ISSUE THREAD

**Issue by vhejral** [lte2000/intellibot#52]
In one of the projects with many files, I am getting stable high CPU usage 55-70% with the plugin installed.
Disabling plugin, uninstall plugin and high CPU load is gone.
I checked previous issue and tried to disable all robot inspections. It did not help. 
How can I troubleshoot what is wrong? I would like to get this high CPU usage down. Thanks for all the good work.

**Comment by lte2000** [comment]
try following settings.

Settings -> Editor -> Inspections -> Robot -> Clean Up -> Import not used : 
  unchecked

Settings -> Languages & Frameworks -> Robot Options
  Max Transitive Imports Depth: 3 or 4 
  Allow Global Variables: unchecked
  Enable Debug Trace: unchecked
  Inline Variable Keyword Search: unchecked

**Comment by vhejral** [comment]
Thank you, the key was the "Max Transitive Imports Depth: 3"
I checked several combinations, but this was the only needed thing to do. I kept all other to defaults (e.g. Imports not used: checked etc.)
Thank you. I am closing this then.
