### ISSUE TITLE
2 to 4 spaces as a configurable setting

### ISSUE THREAD

**Issue by lcmcninch** [lte2000/intellibot#61]
First, thanks so much for maintaining this plugin, I'm so glad that I found this fork!

I'm wondering if the feature that automatically expands 2 spaces to 4 could be a setting that could be turned off? Or maybe it already is and I haven't found it. I generally prefer to stick with 2 spaces. I don't have a sense of how plugins and their settings work so this might not be a straightforward request, but worth asking.

Thanks.

**Comment by lte2000** [comment]
You can uncheck the checkbox in "File -> Settings -> Languages & Frameworks -> Robot Options -> Expand Adjacent 2 or 3 Spaces to 4 Spaces When Type".
You can also find other settings for this plugin in that place.

**Comment by lcmcninch** [comment]
:facepalm: I'm sorry, I should have found that. I'd swear I searched the settings for "robot"... I'm going to blame it on PyCharm's settings search failing me... Thanks so much for the help! And the plugin!
