### ISSUE TITLE
intellibot@seleniumLibrary exception

### ISSUE THREAD

**Issue by sandy958** [lte2000/intellibot#62]
unable to plugin intellibot@seleniumpluginLibrary patched its show some exception
<img width="471" alt="Snag_61184e0c" src="https://github.com/lte2000/intellibot/assets/141119945/72d68841-6562-4e7c-ba72-3bbf6e225660">
<img width="729" alt="Snag_611afc15" src="https://github.com/lte2000/intellibot/assets/141119945/cb98998f-93e4-40e3-b6ca-4d16703e0918">

**Comment by lte2000** [comment]
Please uninstall that plugin, and install  'IntelliBot #patched' from Jetbrain Marketplace.
BTW, they're 2 different plugin.

**Comment by sandy958** [comment]
Thanks
