### ISSUE TITLE
Dialogs library not found - Robot Framework standard library

### ISSUE THREAD

**Issue by Vyrium** [lte2000/intellibot#7]
The screenshot shows that all other libraries can be found except for dialogs.

List of standard libraries
https://robotframework.org/robotframework/

![image](https://user-images.githubusercontent.com/18133707/74516425-40941280-4f08-11ea-93dc-54bbbcde9752.png)

The example above will run however autocomplete is not functioning

![image](https://user-images.githubusercontent.com/18133707/74516910-29095980-4f09-11ea-8fa6-0a46ea095136.png)

Environment: 
PyCharm 2019.2.3
Plugin version: intellibot-dev_0.10.143.388

Packages - Python 3.8:
![image](https://user-images.githubusercontent.com/18133707/74517062-679f1400-4f09-11ea-85dc-49d2c01725a2.png)

Robot Options
![image](https://user-images.githubusercontent.com/18133707/74517440-03308480-4f0a-11ea-8f59-f5d712509fd2.png)

**Comment by lte2000** [comment]
Please try 0.10.143.389.
You can download and install intellibot.jar from https://github.com/lte2000/intellibot

**Comment by Vyrium** [comment]
Can confirm that the latest build solves this issue. 

Many thanks
